### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by peeterx** [ugwulo/Team-Ace-Git-Lab#34]
GitHub account:
![github](https://user-images.githubusercontent.com/29917058/80895425-808bba00-8ced-11ea-9e2a-9a77f2879c61.PNG)

Forked repository:
![forked-repo](https://user-images.githubusercontent.com/29917058/80895434-94372080-8ced-11ea-81be-b78c921c58a0.PNG)

Cloned repository
![cloned-repo](https://user-images.githubusercontent.com/29917058/80895436-98633e00-8ced-11ea-9101-f6df478e6e0c.PNG)

**Comment by ugwulo** [comment]
@peeterx 
You don't need to open a new issue
Check the issues where I said: 'submit your screenshots here's
Thanks
